//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPulse.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysPulse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU –%.
        /// </summary>
        public static string Dock_InitialTitle {
            get {
                return ResourceManager.GetString("Dock_InitialTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MEM –%.
        /// </summary>
        public static string Dock_InitialSubtitle {
            get {
                return ResourceManager.GetString("Dock_InitialSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High CPU.
        /// </summary>
        public static string Dock_AlertHighCpu {
            get {
                return ResourceManager.GetString("Dock_AlertHighCpu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High memory.
        /// </summary>
        public static string Dock_AlertHighMemory {
            get {
                return ResourceManager.GetString("Dock_AlertHighMemory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High CPU &amp; memory.
        /// </summary>
        public static string Dock_AlertHighBoth {
            get {
                return ResourceManager.GetString("Dock_AlertHighBoth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU {0}%.
        /// </summary>
        public static string Dock_CpuTitleFormat {
            get {
                return ResourceManager.GetString("Dock_CpuTitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MEM {0}%.
        /// </summary>
        public static string Dock_MemSubtitleFormat {
            get {
                return ResourceManager.GetString("Dock_MemSubtitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}% | {1}%.
        /// </summary>
        public static string Dock_CompactFormat {
            get {
                return ResourceManager.GetString("Dock_CompactFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top processes.
        /// </summary>
        public static string TopProcesses_Title {
            get {
                return ResourceManager.GetString("TopProcesses_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TopProcesses_OpenName {
            get {
                return ResourceManager.GetString("TopProcesses_OpenName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No process data yet.
        /// </summary>
        public static string TopProcesses_EmptyTitle {
            get {
                return ResourceManager.GetString("TopProcesses_EmptyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sampling processes….
        /// </summary>
        public static string TopProcesses_EmptySubtitle {
            get {
                return ResourceManager.GetString("TopProcesses_EmptySubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy PID.
        /// </summary>
        public static string Command_CopyPid {
            get {
                return ResourceManager.GetString("Command_CopyPid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open file location.
        /// </summary>
        public static string Command_OpenFileLocation {
            get {
                return ResourceManager.GetString("Command_OpenFileLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string Command_Kill {
            get {
                return ResourceManager.GetString("Command_Kill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Command_Refresh {
            get {
                return ResourceManager.GetString("Command_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kill process.
        /// </summary>
        public static string Kill_ConfirmTitle {
            get {
                return ResourceManager.GetString("Kill_ConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kill {0} (PID {1})?.
        /// </summary>
        public static string Kill_ConfirmDescriptionFormat {
            get {
                return ResourceManager.GetString("Kill_ConfirmDescriptionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing to kill..
        /// </summary>
        public static string Kill_NothingToKill {
            get {
                return ResourceManager.GetString("Kill_NothingToKill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: process already exited..
        /// </summary>
        public static string Kill_AlreadyExitedFormat {
            get {
                return ResourceManager.GetString("Kill_AlreadyExitedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} killed..
        /// </summary>
        public static string Kill_SuccessFormat {
            get {
                return ResourceManager.GetString("Kill_SuccessFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot kill {0}: it runs with administrator rights and SysPulse runs unelevated..
        /// </summary>
        public static string Kill_AdminRequiredFormat {
            get {
                return ResourceManager.GetString("Kill_AdminRequiredFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot kill {0}: {1}.
        /// </summary>
        public static string Kill_Win32ErrorFormat {
            get {
                return ResourceManager.GetString("Kill_Win32ErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot kill {0}: unexpected error..
        /// </summary>
        public static string Kill_UnexpectedErrorFormat {
            get {
                return ResourceManager.GetString("Kill_UnexpectedErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot kill {0}: it is protected..
        /// </summary>
        public static string Kill_ProtectedFormat {
            get {
                return ResourceManager.GetString("Kill_ProtectedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot kill {0}'s process tree: {1} is protected..
        /// </summary>
        public static string Kill_TreeProtectedFormat {
            get {
                return ResourceManager.GetString("Kill_TreeProtectedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SysPulse – Top processes.
        /// </summary>
        public static string Provider_TopLevelTitle {
            get {
                return ResourceManager.GetString("Provider_TopLevelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan interval (seconds, 2–300).
        /// </summary>
        public static string Settings_ScanIntervalSeconds_Label {
            get {
                return ResourceManager.GetString("Settings_ScanIntervalSeconds_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How often SysPulse samples CPU and memory while healthy..
        /// </summary>
        public static string Settings_ScanIntervalSeconds_Description {
            get {
                return ResourceManager.GetString("Settings_ScanIntervalSeconds_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry interval (seconds, 1–60).
        /// </summary>
        public static string Settings_RetryIntervalSeconds_Label {
            get {
                return ResourceManager.GetString("Settings_RetryIntervalSeconds_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How often SysPulse re-checks a suspected breach. Must be less than the scan interval..
        /// </summary>
        public static string Settings_RetryIntervalSeconds_Description {
            get {
                return ResourceManager.GetString("Settings_RetryIntervalSeconds_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry count (1–10).
        /// </summary>
        public static string Settings_RetryCount_Label {
            get {
                return ResourceManager.GetString("Settings_RetryCount_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of consecutive retries that must all breach before SysPulse alerts..
        /// </summary>
        public static string Settings_RetryCount_Description {
            get {
                return ResourceManager.GetString("Settings_RetryCount_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitor CPU.
        /// </summary>
        public static string Settings_CpuMonitoringEnabled_Label {
            get {
                return ResourceManager.GetString("Settings_CpuMonitoringEnabled_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether CPU usage counts toward a breach..
        /// </summary>
        public static string Settings_CpuMonitoringEnabled_Description {
            get {
                return ResourceManager.GetString("Settings_CpuMonitoringEnabled_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU threshold (%, 10–100).
        /// </summary>
        public static string Settings_CpuThreshold_Label {
            get {
                return ResourceManager.GetString("Settings_CpuThreshold_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU percent at or above which a breach is considered..
        /// </summary>
        public static string Settings_CpuThreshold_Description {
            get {
                return ResourceManager.GetString("Settings_CpuThreshold_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitor memory.
        /// </summary>
        public static string Settings_MemoryMonitoringEnabled_Label {
            get {
                return ResourceManager.GetString("Settings_MemoryMonitoringEnabled_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Whether memory usage counts toward a breach..
        /// </summary>
        public static string Settings_MemoryMonitoringEnabled_Description {
            get {
                return ResourceManager.GetString("Settings_MemoryMonitoringEnabled_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory threshold (%, 10–100).
        /// </summary>
        public static string Settings_MemoryThreshold_Label {
            get {
                return ResourceManager.GetString("Settings_MemoryThreshold_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory percent at or above which a breach is considered..
        /// </summary>
        public static string Settings_MemoryThreshold_Description {
            get {
                return ResourceManager.GetString("Settings_MemoryThreshold_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hysteresis (%, 0–20).
        /// </summary>
        public static string Settings_HysteresisPercent_Label {
            get {
                return ResourceManager.GetString("Settings_HysteresisPercent_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Margin below a threshold a metric must drop to before SysPulse leaves the alert state..
        /// </summary>
        public static string Settings_HysteresisPercent_Description {
            get {
                return ResourceManager.GetString("Settings_HysteresisPercent_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show a toast on alert.
        /// </summary>
        public static string Settings_ShowToast_Label {
            get {
                return ResourceManager.GetString("Settings_ShowToast_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show a Windows notification the first time an alert episode begins..
        /// </summary>
        public static string Settings_ShowToast_Description {
            get {
                return ResourceManager.GetString("Settings_ShowToast_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm before killing.
        /// </summary>
        public static string Settings_ConfirmKill_Label {
            get {
                return ResourceManager.GetString("Settings_ConfirmKill_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ask for confirmation before killing a process..
        /// </summary>
        public static string Settings_ConfirmKill_Description {
            get {
                return ResourceManager.GetString("Settings_ConfirmKill_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kill process tree.
        /// </summary>
        public static string Settings_KillProcessTree_Label {
            get {
                return ResourceManager.GetString("Settings_KillProcessTree_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Also kill descendant processes when killing a process..
        /// </summary>
        public static string Settings_KillProcessTree_Description {
            get {
                return ResourceManager.GetString("Settings_KillProcessTree_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compact dock label.
        /// </summary>
        public static string Settings_CompactLabel_Label {
            get {
                return ResourceManager.GetString("Settings_CompactLabel_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use a single-line "30% | 50%" dock label instead of the two-line "CPU 30%" / "MEM 50%" label..
        /// </summary>
        public static string Settings_CompactLabel_Description {
            get {
                return ResourceManager.GetString("Settings_CompactLabel_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Never offer Kill for these processes.
        /// </summary>
        public static string Settings_ProtectedProcesses_Label {
            get {
                return ResourceManager.GetString("Settings_ProtectedProcesses_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extra process names, comma-separated, case-insensitive, ".exe" optional..
        /// </summary>
        public static string Settings_ProtectedProcesses_Description {
            get {
                return ResourceManager.GetString("Settings_ProtectedProcesses_Description", resourceCulture);
            }
        }
    }
}
