//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysPulse.Core.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysPulse.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU at {0}%.
        /// </summary>
        public static string Alert_Cpu {
            get {
                return ResourceManager.GetString("Alert_Cpu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory at {0}%.
        /// </summary>
        public static string Alert_Memory {
            get {
                return ResourceManager.GetString("Alert_Memory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU {0}% · memory {1}%.
        /// </summary>
        public static string Alert_Both {
            get {
                return ResourceManager.GetString("Alert_Both", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} for the last ~{1} s..
        /// </summary>
        public static string Alert_ForTheLast {
            get {
                return ResourceManager.GetString("Alert_ForTheLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Top: {0} ({1})..
        /// </summary>
        public static string Alert_TopProcess {
            get {
                return ResourceManager.GetString("Alert_TopProcess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU {0}% · RAM {1} · PID {2}.
        /// </summary>
        public static string ProcessSubtitle_Format {
            get {
                return ResourceManager.GetString("ProcessSubtitle_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  · protected.
        /// </summary>
        public static string ProcessSubtitle_ProtectedSuffix {
            get {
                return ResourceManager.GetString("ProcessSubtitle_ProtectedSuffix", resourceCulture);
            }
        }
    }
}
